title: spenceralessi.com
description: >- # this means to ignore newlines until "baseurl:"
  Family first, but after that I'm an Information Security practitioner, 
  passionate Blue Teamer and lover of Winter.
motto: Live now, be yourself, memento mori.
logo: /assets/img/logo.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techspence.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter: https://twitter.com/techspence
twitter_logo: /assets/img/twitter.png

github:  https://github.com/techspence
github_logo: /assets/img/github.png

repository: https://github.com/techspence/techspence.github.io
theme: jekyll-theme-minimal