title: spenceralessi.com
description: >- # this means to ignore newlines until "baseurl:"
  Family first, but after that I'm an Information Security practitioner, 
  passionate about #BlueTeam and lover of Winter. My current life motto's are:
  Live now and be yourself and Memento Mori, which means remember death.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/techspence/techspence.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: techspence
github_username:  techspence
repository: techspence/techspence.github.io
theme: jekyll-theme-minimal
