title: SpencerAlessi.com
logo: /assets/img/logo.png
description: Family first, but after that I'm an Information Security practitioner, 
  passionate about #BlueTeam and lover of Winter. My current life motto's are:
  Live now and be yourself and Memento Mori, which means remember death.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
